### PR TITLE
Selected theme is always visible.

### PR DESCRIPTION
**Pull request by Asssket**

### CODE REVIEW

**Comment by AlexW00** [comment]
This commit results in an error "e.path is not defined" when clicking on a theme from the theme changer.

**Comment by Asssket** [comment]
> This commit results in an error "e.path is not defined" when clicking on a theme from the theme changer.

Ok. I'll check it in the evening.

**Comment by Asssket** [comment]
> This commit results in an error "e.path is not defined" when clicking on a theme from the theme changer.

Check it again. And I suggest adding $ symbol to start name of variables which refer to html element to immediately understand that is html element

**Comment by AlexW00** [comment]
> > This commit results in an error "e.path is not defined" when clicking on a theme from the theme changer.
> 
> Check it again. And I suggest adding $ symbol to start name of variables which refer to html element to immediately understand that is html element

Thanks for the $ tip, I will refactor the code soon. The `e.path is undefined` bug is still there. However, I found out that it is specific to browsers not built on chromium. 
This change did the trick:
```
const path = e.path || (e.composedPath && e.composedPath());
const selectedTheme = path[1];
```
Thank you for your contribution, I will merge it!

**Comment by AlexW00** [comment]
> 

I created a branch off the pull request, fixed the path bug and merged the branch into master. Your changes are live and your commit is on the master - check the commit history.
No need to create a new pull request :)

**Comment by Asssket** [comment]
> > 
> 
> I created a branch off the pull request, fixed the path bug and merged the branch into master. Your changes are live and your commit is on the master - check the commit history. No need to create a new pull request :)

Second [commit](https://github.com/AlexW00/StartTreeV2/pull/3/commits/ef81cfbb47e7ed260f7d11419e0504ca28937cee) not merged lmao.

**Comment by AlexW00** [comment]
> > > 
> > 
> > 
> > I created a branch off the pull request, fixed the path bug and merged the branch into master. Your changes are live and your commit is on the master - check the commit history. No need to create a new pull request :)
> 
> Second [commit](https://github.com/AlexW00/StartTreeV2/pull/3/commits/ef81cfbb47e7ed260f7d11419e0504ca28937cee) not merged lmao.

Oh crap, sorry I missed it. Should be in now. - sorry for the messy merge.

**Comment by Asssket** [comment]
Thanks. It's working fine now.

**Pull request closed without merging**
